In [1]:
import numpy as np

array_15_by_10_by_20 = np.random.uniform(0, 1, size=(1000, 1000, 1000))
 
print(array_15_by_10_by_20)

[[[0.34481997 0.31431873 0.81073796 ... 0.99322706 0.88487893 0.32906713]
  [0.20227982 0.79494466 0.71199884 ... 0.03149406 0.08589373 0.93538881]
  [0.74007006 0.6928114  0.98160203 ... 0.0811621  0.30083588 0.78088686]
  ...
  [0.19050997 0.80775433 0.10909946 ... 0.94798959 0.65175793 0.15849793]
  [0.68084722 0.17060339 0.8981214  ... 0.00432996 0.72885537 0.79285713]
  [0.85789876 0.19301062 0.37330497 ... 0.62256768 0.54226588 0.92000228]]

 [[0.25037797 0.13941794 0.41208101 ... 0.29022418 0.22061124 0.28021046]
  [0.98787323 0.64270761 0.55875736 ... 0.88898574 0.3483025  0.84538119]
  [0.91433764 0.6360572  0.20495662 ... 0.61508771 0.79139105 0.3392293 ]
  ...
  [0.99921124 0.0557889  0.15521937 ... 0.77026584 0.53236231 0.04032664]
  [0.47883568 0.34127223 0.88404066 ... 0.71947025 0.91558958 0.65399411]
  [0.07684938 0.26270825 0.11136977 ... 0.77078828 0.58354255 0.62127899]]

 [[0.82739099 0.99314743 0.7929301  ... 0.61666445 0.52078055 0.53104735]
  [0.93451785 0.318969

In [55]:
item_count = 1000
select_list = []
count = 0
first_level_random_used = set()
second_level_random_used = set()

while True:
    first_level_random = np.random.randint(1, 1000)
    second_level_random = np.random.randint(1, 1000)
    
    while first_level_random not in first_level_random_used:
        first_level_random_used.add(first_level_random)
        break
    while second_level_random not in second_level_random_used:
        second_level_random_used.add(second_level_random)
        break
    
    for second_array in array_15_by_10_by_20[first_level_random]:
        second_array_mean = np.mean(array_15_by_10_by_20[second_level_random])
        for item in second_array:
            if item > second_array_mean:
                count = count + 1
                select_list.append(item)
            if count >= item_count:
                break
        if count >= item_count:
                break
    if count >= item_count:
                break
print(select_list)
print(len(select_list))
print(np.sum(np.array(select_list)))

[0.523990447843544, 0.673946853721601, 0.7842300973973696, 0.9433252960235945, 0.9137024282230493, 0.9934397309167871, 0.6752432071444446, 0.7320283691190727, 0.969890779823492, 0.8659447337430152, 0.6414096311815501, 0.8073980294750739, 0.5840932215435588, 0.8471593457349632, 0.9174040396007161, 0.7367148610657485, 0.5482399669110035, 0.5206038970868724, 0.7104440733519515, 0.8546120357734, 0.5356478530898046, 0.7856435852723308, 0.6217939946475886, 0.7164877566523735, 0.9488645826820099, 0.6566172746350938, 0.9702096053269164, 0.9159412919090232, 0.9654721912337071, 0.872302370379281, 0.572144355772104, 0.7564678160612013, 0.5942538995534552, 0.7818015313185176, 0.8170136293015327, 0.6741760275983744, 0.7510536850921332, 0.5003311958682776, 0.8589688929286317, 0.6006185820113568, 0.9847853798822277, 0.6460624387597119, 0.8565811942260815, 0.6873674652500786, 0.7227738898607806, 0.8826249549411819, 0.7379670170293314, 0.9263951807696501, 0.6700492289882796, 0.6194142799203911, 0.76892