In [1]:
import numpy as np

array_15_by_10_by_20 = np.random.uniform(0, 1, size=(1000, 1000, 1000))
 
print(array_15_by_10_by_20)

[[[0.84675705 0.89921897 0.1996368  ... 0.09411224 0.21109495 0.36003969]
  [0.24443989 0.38868575 0.96480272 ... 0.04679789 0.64948115 0.06945703]
  [0.20494563 0.26599639 0.52646329 ... 0.15414077 0.5852567  0.45040714]
  ...
  [0.71853002 0.04145786 0.41814016 ... 0.49770239 0.7027411  0.11834215]
  [0.43182288 0.63145867 0.91948513 ... 0.28354927 0.73190416 0.26553852]
  [0.31772814 0.50430994 0.90443622 ... 0.81252161 0.93488535 0.92319902]]

 [[0.37970008 0.49729026 0.24313545 ... 0.54417708 0.45736158 0.80771092]
  [0.80334415 0.87281663 0.40251656 ... 0.91747069 0.57415843 0.29110431]
  [0.96132947 0.67377371 0.72327248 ... 0.0231011  0.88636941 0.8930522 ]
  ...
  [0.20473298 0.36656463 0.55084185 ... 0.27198126 0.84697865 0.89405209]
  [0.88757165 0.15977383 0.90246148 ... 0.47159531 0.91188589 0.29102861]
  [0.98611165 0.88533007 0.48458965 ... 0.63378245 0.6530089  0.8377399 ]]

 [[0.3771813  0.23680298 0.32557066 ... 0.27500033 0.36810217 0.52327753]
  [0.78226484 0.939428

In [7]:
len(array_15_by_10_by_20[0])

1000

In [9]:
len(array_15_by_10_by_20[999])

1000

In [8]:
len(array_15_by_10_by_20[0][0])

1000

In [10]:
item_count = 1000
select_list = []
count = 0
first_level_random_used = set()
second_level_random_used = set()

while True:
    first_level_random = np.random.randint(1, 1000)
    second_level_random = np.random.randint(1, 1000)
    
    while first_level_random not in first_level_random_used:
        first_level_random_used.add(first_level_random)
        break
    while second_level_random not in second_level_random_used:
        second_level_random_used.add(second_level_random)
        break
    
    for second_array in array_15_by_10_by_20[first_level_random]:
        second_array_mean = np.mean(array_15_by_10_by_20[second_level_random])
        for item in second_array:
            if item > second_array_mean:
                count = count + 1
                select_list.append(item)
            if count >= item_count:
                break
        if count >= item_count:
                break
    if count >= item_count:
                break
print(select_list)
print(len(select_list))
print(np.sum(np.array(select_list)))

[0.675258460017226, 0.5715673746069924, 0.5185333359717365, 0.7648116919394423, 0.8603441621663347, 0.5019350810760653, 0.6486178274034453, 0.722048546050049, 0.7364847148730196, 0.5081764465841035, 0.5942617123708959, 0.6994794358128552, 0.5331639996280397, 0.606529741805903, 0.8049338213027433, 0.9332177438116388, 0.8230812197687003, 0.8242829971900835, 0.7201125774255392, 0.7813829897931924, 0.8696578960988771, 0.5619889370453458, 0.63880281474969, 0.5328544908657163, 0.7376461259050712, 0.9703095298632327, 0.5427112973551569, 0.7838218953833995, 0.6504242213662095, 0.6855688607567108, 0.6137539845751478, 0.6156629220747596, 0.5540806447577893, 0.7798500496083969, 0.820365529290183, 0.8152033566668199, 0.6171612199493642, 0.7759189412768075, 0.8399349291857717, 0.6605637393410043, 0.9591256677303235, 0.5200062529588385, 0.7638098965353373, 0.5045777077717444, 0.6720737079562241, 0.6477617321079626, 0.9860017041024933, 0.8772721187793633, 0.6204002787113696, 0.6201944192430412, 0.564